ParkingViolation/Models/Volunteer.cs
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace ParkingViolation.Models
{
	public class Volunteer : Person
	{
		public virtual ICollection<Vehicle> Vehicles { get; set; }
	}
}

ParkingViolation/Controllers/VolunteerController.cs
using System;
using System.Collections.Generic;
using System.Data;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using ParkingViolation.DAL;
using ParkingViolation.Models;

namespace ParkingViolation.Controllers
{
	public class VolunteerController : Controller
	{
		private ParkingViolationContext db = new ParkingViolationContext();

		// GET: Volunteer
		public ActionResult Index(string sortOrder, string searchString) //, string currentFilter)
		{
			ViewBag.CurrentFilter = searchString;
			ViewBag.FirstNameSortOrder = (String.IsNullOrEmpty(sortOrder) ? "FirstName_Desc" : String.Empty);
			ViewBag.LastNameSortOrder = (sortOrder == "LastName_Asc" ? "LastName_Desc" : "LastName_Asc");

			var volunteers = from v in db.Volunteers
							 select v;

			if (!string.IsNullOrEmpty(searchString))
			{
				volunteers = volunteers.Where(v => v.FirstMidName.Contains(searchString) || v.LastName.Contains(searchString));	
			}

			switch (sortOrder)
			{
				case "FirstName_Desc":
					volunteers = volunteers.OrderByDescending(v => v.FirstMidName);
					break;
				case "LastName_Asc":
					volunteers = volunteers.OrderBy(v => v.LastName);
					break;
				case "LastName_Desc":
					volunteers = volunteers.OrderByDescending(v => v.LastName);
					break;
				default:
					volunteers = volunteers.OrderBy(v => v.FirstMidName);
					break;
			}

			//return View(db.Volunteers.ToList());
			return View(volunteers.ToList());
		}

		// GET: Volunteer/Details/5
		public ActionResult Details(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			var volunteer = db.Volunteers.Find(id);
			if (volunteer == null)
			{
				return HttpNotFound();
			}
			return View(volunteer);
		}

		// GET: Volunteer/Create
		public ActionResult Create()
		{
			return View();
		}

		// POST: Volunteer/Create
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Create([Bind(Include = "FirstMidName,LastName,PhoneNumber,EmailAddress")] Volunteer volunteer)
		{
			try
			{
				if (PhoneNumberAlreadyInUse(volunteer.PhoneNumber))
				{
					ModelState.AddModelError("PhoneNumber", "Phone number is already associated with another urser.");
				}

				if (ModelState.IsValid)
				{
					db.People.Add(volunteer);
					db.SaveChanges();
					return RedirectToAction("Index");
				}
			}
			catch (DataException)
			{
				ModelState.AddModelError("", "Unable to save changes. Try again.");
			}

			return View(volunteer);
		}

		// GET: Volunteer/Edit/5
		public ActionResult Edit(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}
			var volunteer = db.Volunteers.Find(id);
			if (volunteer == null)
			{
				return HttpNotFound();
			}
			return View(volunteer);
		}

		// POST: Volunteer/Edit/5
		// To protect from overposting attacks, please enable the specific properties you want to bind to, for 
		// more details see http://go.microsoft.com/fwlink/?LinkId=317598.
		[HttpPost]
		[ActionName("Edit")]
		[ValidateAntiForgeryToken]
		//public ActionResult Edit([Bind(Include = "FirstMidName,LastName,PhoneNumber,EmailAddress")] Volunteer volunteer)
		public ActionResult EditPost(int? id)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			var volunteerToUpdate = db.Volunteers.Find(id);
			var initialPhoneNumber = volunteerToUpdate.PhoneNumber;

			if (TryUpdateModel(volunteerToUpdate, "", new string[] { "FirstMidName", "LastName", "PhoneNumber", "EmailAddress" }))
			{
				try
				{
					if ((volunteerToUpdate.PhoneNumber != initialPhoneNumber) && (PhoneNumberAlreadyInUse(volunteerToUpdate.PhoneNumber)))
					{
						ModelState.AddModelError("PhoneNumber", "Phone number is already associated with another urser.");
					}

					if (ModelState.IsValid)
					{
						db.SaveChanges();
						return RedirectToAction("Index");
					}
				}
				catch (DataException)
				{
					ModelState.AddModelError("", "Unable to save changes. Try again.");
				}
			}

			return View(volunteerToUpdate);
		}

		// GET: Volunteer/Delete/5
		public ActionResult Delete(int? id, bool? saveChangesError = false)
		{
			if (id == null)
			{
				return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
			}

			var volunteer = db.Volunteers.Find(id);

			if (volunteer == null)
			{
				return HttpNotFound();
			}

			if (saveChangesError.GetValueOrDefault())
			{
				ViewBag.ErrorMessage = "Delete failed. Try again.";
			}

			return View(volunteer);
		}

		// POST: Volunteer/Delete/5
		[HttpPost]
		[ValidateAntiForgeryToken]
		public ActionResult Delete(int id)
		{
			try
			{
				//var volunteer = db.Volunteers.Find(id);
				//db.Volunteers.Remove(volunteer);
				var volunteerToDelete = new Volunteer { PersonID = id };
				db.Entry(volunteerToDelete).State = EntityState.Deleted;
				db.SaveChanges();
			}
			catch (DataException)
			{
				return RedirectToAction("Delete", new { id = id, saveChangesError = true });
			}
			return RedirectToAction("Index");
		}

		protected override void Dispose(bool disposing)
		{
			if (disposing)
			{
				db.Dispose();
			}
			base.Dispose(disposing);
		}

		public ActionResult ValidatePhoneNumber(string PhoneNumber, string initialPhoneNumber)
		{
			if (PhoneNumber == initialPhoneNumber)
			{
				return Json(true, JsonRequestBehavior.AllowGet);
			}

			return Json(!db.Volunteers.Any(v => v.PhoneNumber == PhoneNumber), JsonRequestBehavior.AllowGet);
		}

		public bool PhoneNumberAlreadyInUse(string PhoneNumber)
		{
			return db.Volunteers.Any(v => v.PhoneNumber == PhoneNumber);
		}
	}
}

ParkingViolation/Views/Volunteer/Create.cshtml
@model ParkingViolation.Models.Volunteer

@{
	ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm())
{
	@Html.AntiForgeryToken()

	<div class="form-horizontal">
		<h4>Volunteer</h4>
		<hr />
		@Html.ValidationSummary(true, "", new { @class = "text-danger" })
		<div class="form-group">
			@Html.LabelFor(model => model.FirstMidName, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.FirstMidName, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.FirstMidName, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			@Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
			<div class="col-md-10">
				@Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
				@Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
			</div>
		</div>

		<div class="form-group">
			<div class="col-md-offset-2 col-md-10">
				<input type="submit" value="Create" class="btn btn-default" />
			</div>
		</div>
	</div>
}

<div>
	@Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
	@Scripts.Render("~/bundles/jqueryval")
}

ParkingViolation/Views/Volunteer/Delete.cshtml
@model ParkingViolation.Models.Volunteer

@{
	ViewBag.Title = "Delete";
}

<h2>Delete Volunteer</h2>
<h3>Are you sure you want to delete @Html.DisplayFor(model => model.FullName)?</h3>
<div>
	@*<h4>Volunteer</h4>*@
	<hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.FirstMidName)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.FirstMidName)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.LastName)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.LastName)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.PhoneNumber)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.PhoneNumber)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.EmailAddress)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.EmailAddress)
		</dd>

	</dl>

	@using (Html.BeginForm())
	{
		@Html.AntiForgeryToken()

		<div class="form-actions no-color">
			<input type="submit" value="Delete" class="btn btn-default" />
			<span class="text-danger"><br />@ViewBag.ErrorMessage</span>
			<br />
			@Html.ActionLink("Back to List", "Index")
		</div>
	}
</div>

ParkingViolation/Views/Volunteer/Details.cshtml
@model ParkingViolation.Models.Volunteer

@{
	ViewBag.Title = "Volunteer Details";
}

<h2>@Model.FirstMidName's Details</h2>

<div>
	<h4>Volunteer</h4>
	<hr />
	<dl class="dl-horizontal">
		<dt>
			@Html.DisplayNameFor(model => model.FirstMidName)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.FirstMidName)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.LastName)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.LastName)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.PhoneNumber)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.PhoneNumber)
		</dd>

		<dt>
			@Html.DisplayNameFor(model => model.EmailAddress)
		</dt>

		<dd>
			@Html.DisplayFor(model => model.EmailAddress)
		</dd>
		<dt>
			@Html.DisplayNameFor(model => model.Vehicles)
		</dt>
		<dd>
			@if (Model.Vehicles.Count > 0)
			{
				<text>@Model.Vehicles.Count vehicle(s) are register</text>
				<table class="table">
					<tr>
						<th>Number Plate</th>
						<th># of Violations</th>
					</tr>
					@foreach (var item in Model.Vehicles)
					{
						<tr>
							<td>@Html.DisplayFor(modelItem => item.State) @Html.DisplayFor(modelItem => item.NumberPlate)</td>
							<td>@Html.DisplayFor(modelItem => item.Violations.Count)</td>
						</tr>
					}
				</table>
			}
			else
			{
				<text>0 vehicles are register.</text>
			}
		</dd>
	</dl>
</div>
<p>
	@Html.ActionLink("Edit", "Edit", new { id = Model.PersonID }) |
	@Html.ActionLink("Back to List", "Index")
</p>

ParkingViolation/Views/Volunteer/Edit.cshtml
@model ParkingViolation.Models.Volunteer

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Volunteer</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.PersonID)
		@Html.Hidden("initialPhoneNumber", Model.PhoneNumber)

        <div class="form-group">
            @Html.LabelFor(model => model.FirstMidName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.FirstMidName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.FirstMidName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LastName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.LastName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.LastName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PhoneNumber, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PhoneNumber, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PhoneNumber, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.EmailAddress, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.EmailAddress, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.EmailAddress, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ParkingViolation/Views/Volunteer/Index.cshtml
@model IEnumerable<ParkingViolation.Models.Volunteer>

@{
	ViewBag.Title = "Volunteers";
}

<h2>Volunteers</h2>

<p>
	@Html.ActionLink("Create New", "Create")
</p>

@using (Html.BeginForm("Index", "Volunteer", FormMethod.Get))
{
	<p>
		Filter by Name: @Html.TextBox("searchString")
		<input type="submit" value="Search" />
	</p>
}

<table class="table">
	<tr>
		<th>
			@Html.ActionLink(Html.DisplayNameFor(m => m.FirstMidName).ToHtmlString(), "Index", new { sortOrder = ViewBag.FirstNameSortOrder, searchString = ViewBag.CurrentFilter })
		</th>
		<th>
			@Html.ActionLink(Html.DisplayNameFor(m => m.LastName).ToHtmlString(), "Index", new { sortOrder = ViewBag.LastNameSortOrder, searchString = ViewBag.CurrentFilter })
		</th>
		<th>
			@Html.DisplayNameFor(model => model.PhoneNumber)
		</th>
		<th>
			@Html.DisplayNameFor(model => model.EmailAddress)
		</th>
		<th></th>
	</tr>

	@foreach (var item in Model)
	{
		<tr>
			<td>
				@Html.ActionLink(@Html.DisplayFor(modelItem => item.FirstMidName).ToString(), "Details", new { id = item.PersonID })
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.LastName)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.PhoneNumber)
			</td>
			<td>
				@Html.DisplayFor(modelItem => item.EmailAddress)
			</td>
			<td>
				@Html.ActionLink("Edit", "Edit", new { id = item.PersonID }) |
				@*@Html.ActionLink("Details", "Details", new { id = item.PersonID }) |*@
				@Html.ActionLink("Delete", "Delete", new { id = item.PersonID })
			</td>
		</tr>
	}
</table>